<link
      href="assets/animate.css/animate.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="assets/fontawesome/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,800,900"
      rel="stylesheet"
    />
    <link
      href="assets/chosen/chosen.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="assets/jquery-ui-custom/jquery-ui.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="assets/pentix/css/pentix.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="assets/css/pex-theme.min.css"
      rel="stylesheet"
      type="text/css"
    />